language: ruby
rvm:
- 2.2.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: YC8Ut9jbvAtkGtoswyq/w1OIldcyZJHHms7Q0g2CEJV8fiAYCG/EUUqSiMb1aIssJnd2UztdKfCq1otdB11R651JbNf4jLDuSVGJq9pqfnXy2Ts8xuA6imnqu91HU/5srbwONx9l3+S0Pfhn605Cp368HPayF8t21SjKTMFrhoU=
  app: recipe-o-matic-4000
  run: rake db:migrate
